version: '3.8'

services:
  cortex-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cortex-website
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000
      GITHUB_URL: https://github.com/cortex-web-framework/cortex
      TWITTER_URL: https://twitter.com/cortex_framework
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount logs if needed
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
    driver: local

networks:
  default:
    name: cortex-network
    driver: bridge
