/**
 * Cortex UI Custom Utilities - NO external dependencies
 * Central export point for all utility functions
 */

// Array utilities
export {
  chunk,
  unique,
  uniqueBy,
  flatten,
  findIndex,
  groupBy,
  sortBy,
  removeDuplicates,
  all,
  any,
  count,
  sum,
  average,
  min,
  max,
  range,
  fill,
  transpose,
  zip,
  partition,
  compact,
  intersection,
  difference,
  move,
  shuffle,
  sample,
} from './array.js';

// String utilities
export {
  capitalize,
  camelCase,
  pascalCase,
  kebabCase,
  snakeCase,
  constantCase,
  truncate,
  repeat,
  padLeft,
  padRight,
  trim,
  trimLeft,
  trimRight,
  reverse,
  startsWith,
  endsWith,
  includes,
  indexOf,
  lastIndexOf,
  split,
  join,
  replaceFirst,
  replaceLast,
  replaceAll,
  between,
  countOccurrences,
  isEmpty,
  isNotEmpty,
  escapeHtml,
  unescapeHtml,
  slugify,
  initials,
  isNumeric,
  isAlpha,
  isAlphanumeric,
  titleCase,
} from './string.js';

// Validation utilities
export {
  validateEmail,
  validatePassword,
  validatePhone,
  validateURL,
  validateRequired,
  validateMinLength,
  validateMaxLength,
  validateLength,
  validatePattern,
  validateNumberRange,
  validateMin,
  validateMax,
  validateCreditCard,
  validateDateFormat,
  validateFutureDate,
  validatePastDate,
  validateUsername,
  validateSlug,
  hasUppercase,
  hasLowercase,
  hasNumber,
  hasSpecialChar,
  validateMatch,
  createValidator,
  validateWith,
} from './validation.js';

// Format utilities
export {
  formatCurrency,
  formatPercent,
  formatNumber,
  formatFileSize,
  formatDate,
  formatTime,
  formatRelativeTime,
  formatDuration,
  formatPhone,
  formatCreditCard,
  formatOrdinal,
  formatBinary,
  formatDecimal,
  truncateText,
  formatJSON,
  format,
} from './format.js';

// Storage utilities
export {
  getItem,
  setItem,
  removeItem,
  clear,
  hasItem,
  keys,
  getAll,
  getSize,
  onStorageChange,
  createStorage,
  createSessionStorage,
  createMemoryStorage,
} from './storage.js';

// Event utilities
export {
  debounce,
  throttle,
  once,
  memoize,
  retry,
  on,
  once_event,
  emit,
  onCustom,
  waitForEvent,
  waitForCustomEvent,
  batch,
  chain,
  onWhen,
} from './events.js';

// DOM utilities
export {
  query,
  queryAll,
  getParent,
  getParentMatching,
  getChildren,
  getChildrenMatching,
  getSiblings,
  getNextSibling,
  getPreviousSibling,
  getStyle,
  setStyle,
  setStyles,
  getText,
  setText,
  getHTML,
  setHTML,
  getAttribute,
  setAttribute,
  setAttributes,
  removeAttribute,
  hasClass,
  addClass,
  addClasses,
  removeClass,
  removeClasses,
  toggleClass,
  getClasses,
  createElement,
  append,
  appendChildren,
  prepend,
  insertBefore,
  insertAfter,
  remove,
  clear as clearElement,
  replace,
  clone,
  getElementAtPosition,
  getBounds,
  isInViewport,
  scrollIntoView,
  getScroll,
  setScroll,
  matches,
  getIndex,
  focus,
  blur,
} from './dom.js';
